language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

matrix:
  allow_failures:
    - rust: nightly

